### ISSUE TITLE
[TASK] [#163]

### ISSUE THREAD

**Issue by DarioD99** [AgileNix/coderslang-feedback#163]
I'm getting an error in the terminal 

### Your code
```js
export const startProgressBar = (progressBar, delay) => {
  const timer = setInterval(() => {
    progressBar.tick();
    if (progressBar.complete) {
      console.log('DONE!');
      clearInterval(progressBar)
    }
  }, 100);
}
```

### The output of the terminal with an error if exists
 progressBar.tick();
                ^

TypeError: progressBar.tick is not a function

**Comment by AgileNix** [comment]
@DarioD99 could you post the piece of code that imports the progress bar module and calls the function `startProgressBar`?

**Comment by DarioD99** [comment]
```js
import { startProgressBar } from './functions.js';
import ProgressBar from 'progress';

const bar = new ProgressBar(':bar :percent', { total: 100 })
startProgressBar(100);
```

**Comment by AgileNix** [comment]
@DarioD99 you're calling `startProgressBar` without passing `bar` into it.

**Comment by lukadarko** [comment]
Hi, I tried to solve this task, the bar works but the message DONE! It is repeated indefinitely.
below the code:
file: functions.js
export const startProgressBar = (progressBar, delay) => {
const timer = setInterval(() => {
progressBar.tick();
if (progressBar.complete) {
console.log('DONE!');
clearInterval(progressBar);
}
}, 100);
}

file solution.js

/**
* Implement the function delayedLog(s, n)
*
* It should print the string `s` to the console after `n` seconds.
*
* */

import { delayedLog } from './functions.js';
delayedLog('1 second..', 1);
delayedLog('2 seconds..', 2);
delayedLog('4 seconds..', 4);
delayedLog('8 seconds..', 8);

Thanks for the reply!

**Comment by lukadarko** [comment]
Hi, 
sorry I was wrong, this is the correct solution file:
/**
 * Fix the function `startProgressBar`
 *
 * Expected behavior:
 * The function should display the progress bar on the screen and move it forward each `delay` ms.
 * The interval should be cleared once the progress bar is full.
 *
 * */

import { startProgressBar } from './functions.js';
import ProgressBar from 'progress';

const bar = new ProgressBar(':bar :percent', { total: 100 })
startProgressBar(bar, 100);
